In [32]:
!pip install kagglehub
import kagglehub

# Download latest version
path = kagglehub.dataset_download("saurabhshahane/twitter-sentiment-dataset")

print("Path to dataset files:", path)

Requirement already satisfied: kagglehub in d:\social-media-analysis\.venv\lib\site-packages (1.0.0)
Requirement already satisfied: kagglesdk<1.0,>=0.1.14 in d:\social-media-analysis\.venv\lib\site-packages (from kagglehub) (0.1.16)
Requirement already satisfied: packaging in d:\social-media-analysis\.venv\lib\site-packages (from kagglehub) (26.0)
Requirement already satisfied: pyyaml in d:\social-media-analysis\.venv\lib\site-packages (from kagglehub) (6.0.3)
Requirement already satisfied: requests in d:\social-media-analysis\.venv\lib\site-packages (from kagglehub) (2.32.5)
Requirement already satisfied: tqdm in d:\social-media-analysis\.venv\lib\site-packages (from kagglehub) (4.67.3)
Requirement already satisfied: protobuf in d:\social-media-analysis\.venv\lib\site-packages (from kagglesdk<1.0,>=0.1.14->kagglehub) (6.33.5)
Requirement already satisfied: charset_normalizer<4,>=2 in d:\social-media-analysis\.venv\lib\site-packages (from requests->kagglehub) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in d:\social-media-analysis\.venv\lib\site-packages (from requests->kagglehub) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in d:\social-media-analysis\.venv\lib\site-packages (from requests->kagglehub) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in d:\social-media-analysis\.venv\lib\site-packages (from requests->kagglehub) (2026.2.25)
Requirement already satisfied: colorama in d:\social-media-analysis\.venv\lib\site-packages (from tqdm->kagglehub) (0.4.6)

[notice] A new release of pip is available: 24.3.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

KeyboardInterrupt:

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("../data/twitter_data.csv")

In [ ]:
df.head()

                                          clean_text  category
0  when modi promised “minimum government maximum...      -1.0
1  talk all the nonsense and continue all the dra...       0.0
2  what did just say vote for modi  welcome bjp t...       1.0
3  asking his supporters prefix chowkidar their n...       1.0
4  answer who among these the most powerful world...       1.0

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 162980 entries, 0 to 162979
Data columns (total 2 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   clean_text  162976 non-null  str
 1   category    162973 non-null  float64
dtypes: float64(1), str(1)
memory usage: 21.9 MB

In [33]:
print(df['category'].isnull().sum())

7

In [34]:
df[df['category'].isnull()]

                                               clean_text  category
130448  the foundation stone northeast gas grid inaugu...       NaN
155642  dear terrorists you can run but you cant hide ...       NaN
155698  offense the best defence with mission shakti m...       NaN
155770  have always heard politicians backing out thei...       NaN
158693  modi government plans felicitate the faceless ...       NaN
159442               chidambaram gives praises modinomics       NaN
160559  the reason why modi contested from seats 2014 ...       NaN

In [35]:
df = df.dropna(subset=['category'])

In [36]:
df['category'] = df['category'].astype(int)

In [37]:
print(df['category'].value_counts())

category
 1    72250
 0    55213
-1    35510
Name: count, dtype: int64

In [38]:
df = df.rename(columns={
    'clean_text': 'text',
    'category': 'sentiment'
})

In [40]:
df.info()

<class 'pandas.DataFrame'>
Index: 162973 entries, 0 to 162979
Data columns (total 2 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   text       162969 non-null  str
 1   sentiment  162973 non-null  int64
dtypes: int64(1), str(1)
memory usage: 23.1 MB

In [41]:
df.shape

(162973, 2)

In [43]:
df.to_csv("../data/cleaned_twitter_data.csv", index=False)